name: assets_audio_player
description: Demonstrates how to use the assets_audio_player plugin.
publish_to: "none"
version: 3.0.0

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_neumorphic: ^3.2.0
  rxdart: ^0.27.0
  # for local file test
  dio: ^5.2.1+1
  path_provider: ^2.0.1
  http: ^1.1.0
  provider: ^6.0.0
  file: ^7.0.0
  #flutter_html: ^2.2.1

  # flutter_audio_recorder: ^0.5.5
  # Replaced with record package as flutter_audio_recorder repo is broken
  record: ^5.1.2

  #flutter_audio_query: ^0.3.5+6
  # Replaced with on_audio_query as flutter_audio_query is broken
  on_audio_query: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_web_compilers: ^4.0.4
  pedantic: ^1.11.0

dependency_overrides:
  file: ^7.0.0

  # uncomment to use remote repos
  # assets_audio_player: ^3.0.0
  # assets_audio_player_web: ^3.0.0

  # uncomment to match local repos
  assets_audio_player_plus:
    path: ../
  # assets_audio_player_web:
  #  path: ../assets_audio_player_web

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/images/
  fonts:
    - family: AssetAudioPlayer
      fonts:
        - asset: fonts/AssetAudioPlayer.ttf
